ui:
  ssl: false
  host: rihomolog.furg.br
  port: 4000
  nameSpace: /

rest:
  ssl:  true
  host: rihomolog.furg.br
  port: 443
  nameSpace: /server

themes:

  - name: furg
    headTags:
    - tagName: link
      attributes:
        rel: icon
        href: assets/dspace/images/favicons/favicon.ico
        sizes: any
    - tagName: link
      attributes:
        rel: icon
        href: assets/dspace/images/favicons/favicon.svg
        type: image/svg+xml
    - tagName: link
      attributes:
        rel: apple-touch-icon
        href: assets/dspace/images/favicons/apple-touch-icon.png
    - tagName: link
      attributes:
        rel: manifest
        href: assets/dspace/images/favicons/manifest.webmanifest

